// @flow

export default {
  LOCAL_STATE_MY_STORES_SORT_OPTION_CHANGED: 'LOCAL_STATE_MY_STORES_SORT_OPTION_CHANGED',
  LOCAL_STATE_MY_PRODUCTS_SORT_OPTION_CHANGED: 'LOCAL_STATE_MY_PRODUCTS_SORT_OPTION_CHANGED',
};
